config/routes.rb
Rails.application.routes.draw do

  #get 'post/new'
  resources :posts
  resources :users
  resources :sessions
#  get 'welcome/homepage'
  get 'login' => 'sessions#new'
  
   root 'welcome#homepage'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content

  validates :title, :content, :presence => true
  validates :title, :length => { :minimum => 2}
  validates :title, :uniqueness => { :message => "already taken" }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email,:password, :password_confirmation

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized!" if current_user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authorize, only: [:create, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
       redirect_to posts_path, :notice => "Post Submited!"
    else
      render "new"
  end
end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to post_path, :notice => "Your post has been updated"
    else
      render "edit"
  end
end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, :notice => "Your post has been deleted"

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
  user = User.find_by_email(params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Logged in!"
  else
    flsh.now.alert = "Email or password is invalid"
    render "new"
  end
end
def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: "Logged out!"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    redirect_to root_url, notice:"You signed up!"
  else
    render "new"
  end
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fgamingcommunity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <p><%= value %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<h2>Errors:</h2>
<ul>
  <% @post.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<p>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :content %><br />
  <%= f.text_area :content %>
</p>
<%= f.submit "Submit changes" %>
</p>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <h2><%= link_to post.title, post %></h2>
  <p><%= post.content %></p>
<p>
  <%= link_to "Edit", edit_post_path(post) %>
  <%= link_to "Delete", post, :data => {:confirm => 'Are you sure?'}, :method => :delete %>
</p>
  <hr />
<% end %>

<p><%= link_to "Submit a new Post", new_post_path %></p>

app/views/posts/new.html.erb
<h1> Submit a new post </h1>

<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <h2>Errors:</h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit "Add a New Post" %>
  </p>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<small><%= @post.created_at %></small>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="error_messages">
  <h2>Form is invalid</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %>
</div>
<div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/homepage.html.erb
<h1>Welcome#homepage</h1>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/freelancer.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">


<hr />
</head>
  <div id="container">
   <div id="user_header">
     <% if current_user %>
     Logged in as <%= current_user.email %>
     <%= link_to "Log Out", session_path("current"), method: "delete" %>
  <% end%>
  </div>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">

            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">FAQS Gaming Community</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#portfolio">Posts</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">Community rules</a>
                    </li>
                      <%= link_to "Log In", new_session_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <img class="img-responsive" src="assets/profile.png" alt="">
                    <div class="intro-text">
                        <span class="name">FGC</span>
                        <hr class="star-light">
                        <span class="skills">Answers - Boards - News</span>
                    </div>
                </div>
            </div>
        </div>
    </header>




    <!--  Grid Section -->
    <section id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Posts</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                      <%= link_to image_tag("/assets/portfolio/cabin.jpg"), posts_path %>
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="assets/portfolio/cake.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="assets/portfolio/circus.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="assets/portfolio/game.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="assets/portfolio/safe.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="assets/portfolio/submarine.png" class="img-responsive" alt="">
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Rules</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-lg-offset-2">
                    <p>The FGC is here to give Answers to the most commonly asked questions about games! Remember to mark your posts with tags for spoilers, don't post NSFW content and ALWAYS be respectful to the other users.</p>
                </div>
                <div class="col-lg-4">
                    <p>When submiting a question remember to especify the game and platform! Help the other users providing text, images or links.</p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <%= link_to "Sign Up", new_user_path %>

                    </a>
                </div>
            </div>
        </div>
    </section>



    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Report problems</h3>
                        <p>Having any trouble?<br>Contact us.</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Gaming News</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About </h3>
                        <p>You have the questions, we have the answers! Be sure to follow us at <a href="http://twitter.com/GameFAQs">twitter.com/FGC</a>.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Iago Carvalho 2016
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button  -->
    <div class="scroll-top page-scroll visible-xs visible-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>



    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/freelancer.js"></script>

</body>

</html>